<?php

class UserControllerBack extends Controller
{
    public function saveAction($params = [], $multiple = false, $table = false)
    {
        if (isset($params[Routing::PARAMS_POST]['password'])) {
            if (!empty($params[Routing::PARAMS_POST]['password'])) {
                $params[Routing::PARAMS_POST]['password'] = Hash::generate($params[Routing::PARAMS_POST]['password']);
            }
        }
        return parent::saveAction($params, $multiple, $table); // TODO: Change the autogenerated stub
    }
}
